---
- name: Install Apache on Ubuntu
  hosts: all
  become: yes
  
  tasks:
    - name: Install mysql & apache2
      apt:
        update_cache: yes
        name: "{{ item }}"
        state: present
      loop: 
        - apache2
        - mysql-server  
          
    - name: Modification du fichier html après verification de l'installation de apache2
      ansible.builtin.blockinfile:
        path: /var/www/html/index.html
        block: |
          Bonjour depuis ansible
      when: apache_install is defined and apache_install.changed


    - name: Démarrer et activer Apache2
      ansible.builtin.service:
        name: apache2
        state: restarted
        enabled: yes        
